# Generated by Django 5.2.5 on 2026-05-04 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_assistant', '0003_assistantstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantstatus',
            name='est_actif',
            field=models.BooleanField(default=False),
        ),
    ]
