# Generated by Django 5.2.5 on 2026-06-09 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_assistant', '0004_assistantstatus_est_actif'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppareilConnecte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type_appareil', models.CharField(choices=[('television', 'Télévision'), ('climatiseur', 'Climatiseur'), ('microonde', 'Micro-ondes'), ('led', 'LED / Ampoule'), ('autre', 'Autre')], max_length=20)),
                ('protocole', models.CharField(choices=[('wifi', 'WiFi (HTTP local)'), ('mqtt', 'MQTT'), ('ble', 'Bluetooth BLE'), ('ir', 'Infrarouge (via hub)'), ('zigbee', 'Zigbee (via hub)')], default='wifi', max_length=10)),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('adresse_mac', models.CharField(blank=True, max_length=17, null=True)),
                ('topic_mqtt', models.CharField(blank=True, max_length=200, null=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appareils', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Appareil connecté',
                'unique_together': {('utilisateur', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='CommandeAppareil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commande', models.CharField(max_length=50)),
                ('parametres', models.JSONField(blank=True, default=dict)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('envoyee', 'Envoyée'), ('succes', 'Succès'), ('echec', 'Échec')], default='en_attente', max_length=20)),
                ('source', models.CharField(default='vocal', max_length=10)),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('appareil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='api_assistant.appareilconnecte')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_commande'],
            },
        ),
        migrations.CreateModel(
            name='EtatAppareil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allume', models.BooleanField(default=False)),
                ('temperature', models.IntegerField(blank=True, null=True)),
                ('mode_clim', models.CharField(blank=True, max_length=20, null=True)),
                ('luminosite', models.IntegerField(blank=True, null=True)),
                ('couleur', models.CharField(blank=True, max_length=7, null=True)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('chaine', models.CharField(blank=True, max_length=50, null=True)),
                ('mis_a_jour', models.DateTimeField(auto_now=True)),
                ('appareil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='etat', to='api_assistant.appareilconnecte')),
            ],
        ),
    ]
