# Generated by Django 5.2.5 on 2026-06-19 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_assistant', '0005_appareilconnecte_commandeappareil_etatappareil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appareilconnecte',
            name='canal',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='appareilconnecte',
            name='protocole',
            field=models.CharField(choices=[('wifi', 'WiFi (HTTP local)'), ('mqtt', 'MQTT'), ('ble', 'Bluetooth BLE'), ('ir', 'Infrarouge (via hub)'), ('zigbee', 'Zigbee (via hub)')], default='mqtt', max_length=10),
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('esp32_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pièce',
                'unique_together': {('utilisateur', 'nom')},
            },
        ),
        migrations.AddField(
            model_name='appareilconnecte',
            name='piece',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appareils', to='api_assistant.piece'),
        ),
    ]
