# Generated by Django 5.2.5 on 2026-06-19 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_assistant', '0007_playlist_morceauplaylist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppInstallee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('package', models.CharField(max_length=200)),
                ('date_sync', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps_installees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Application installée',
                'unique_together': {('utilisateur', 'nom')},
            },
        ),
    ]
