# Generated by Django 5.2.1 on 2026-07-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_assistant', '0008_appinstallee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appareilconnecte',
            name='protocole',
            field=models.CharField(choices=[('wifi', 'WiFi (HTTP local)'), ('mqtt', 'MQTT'), ('ble', 'Bluetooth BLE'), ('ir', 'Infrarouge (via hub)'), ('zigbee', 'Zigbee (via hub)'), ('unity', 'Maison virtuelle Unity')], default='mqtt', max_length=10),
        ),
    ]
